config/routes.rb
Saved::Application.routes.draw do
  get "profiles/show"

  as :user do
    get "/register", to: "devise/registrations#new", as: :register
    get "/login", to: "devise/sessions#new", as: :login
    get "/logout", to: "devise/sessions#destroy", as: :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    get "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      put :accept
    end
  end

  resources :testimonies
  get 'feed', to: 'testimonies#index', as: :feed
  root :to => "testimonies#index"

  get '/:id', to: 'profiles#show', as: 'profile'

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
  	@user = User.find_by_profile_name(params[:id])
  	if @user
  		@testimonies = @user.testimonies.all
  		render actions: :show
  	else
  		render  file: 'public/404', status: 404, formats: [:html]
  	end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/show.html.erb
<div class="page-header">
	<h1><%= @user.full_name %></h1>
	<%= image_tag @user.gravatar_url %>
	<%= link_to "Add Friend", new_user_friendship_path(friend_id: @user), class: 'btn' %>
</div>

<% if @testimonies %>
	<% @testimonies.each do |testimony| %>
		<div class="well">
			<%= testimony.content %>
			<br />
			<%= link_to time_ago_in_words(testimony.created_at), testimony_path(testimony) %> ago
		</div>
	<% end %>	
<% end %>	