config/routes.rb
Saved::Application.routes.draw do
  get "profiles/show"

  as :user do
    get "/register", to: "devise/registrations#new", as: :register
    get "/login", to: "devise/sessions#new", as: :login
    get "/logout", to: "devise/sessions#destroy", as: :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    get "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      put :accept
    end
  end

  resources :testimonies
  get 'feed', to: 'testimonies#index', as: :feed
  root :to => "testimonies#index"

  get '/:id', to: 'profiles#show', as: 'profile'

end

app/models/user_friendship.rb
class UserFriendship < ActiveRecord::Base
	belongs_to :user
	belongs_to :friend, class_name: "User", foreign_key: "friend_id"

	attr_accessible :user, :friend, :user_id, :friend_id, :state

	after_destroy :delete_mutual_friendship

	state_machine :state, initial: :pending do
		after_transition on: :accept, do: [:send_acceptance_email, :accept_mutual_friendship!]

		state :requested
		#on the 'accept!' event transition from any state to the 'accepted' state
		#automatically creates 'accept!' method and sets state to 'accepted'
		event :accept do
			transition any => :accepted
		end
	end

	#creates 2 UserFriendship objects
	def self.request(user1, user2)
		transaction do
			friendship1 = create!(user: user1, friend: user2, state: 'pending')
			friendship2 = create!(user: user2, friend: user1, state: 'requested')

			friendship1.send_request_email
			friendship1
		end
	end

	def send_request_email
		#send in instance 'id' only since method is inside UserFriendship model
		UserNotifier.friend_requested(id).deliver
	end

	def send_acceptance_email
		#send in instance 'id' only since method is inside UserFriendship model
		UserNotifier.friend_request_accepted(id).deliver
	end

		#find the inverse (mirror friendship object) of the initially created user_friendship instance
	def mutual_friendship
		self.class.where({user_id: friend_id, friend_id: user_id}).first		
	end

	#get mutual friendship and update the state without using state machine so won't invoke callbacks
	def accept_mutual_friendship!
		mutual_friendship.update_attribute(:state, 'accepted')
	end

	#delete the inverse friendship object
	def delete_mutual_friendship
		mutual_friendship.delete
	end
end

app/controllers/user_friendships_controller.rb
class UserFriendshipsController < ApplicationController
	before_filter :authenticate_user!

	def index
		@user_friendships = current_user.user_friendships.all
	end

	def accept
		@user_friendship = current_user.user_friendships.find(params[:id])
		if @user_friendship.accept!
			flash[:success] = "You are now friends with #{@user_friendship.friend.first_name}"
		else
			flash[:error] = "That friendship cound not be accepted"
		end
		redirect_to user_friendships_path
	end

	def new
		#friend_id is profile name
		if params[:friend_id]
			@friend = User.where(profile_name: params[:friend_id]).first

			raise ActiveRecord::RecordNotFound if @friend.nil?
			@user_friendship = current_user.user_friendships.new(friend: @friend)
		else
			flash[:error] = "Friend required"
		end

	#if friend_id can't be found	
	rescue ActiveRecord::RecordNotFound
		render file: 'public/404', status: :not_found
	end

	def create
		if params[:user_friendship] && params[:user_friendship].has_key?(:friend_id)
			@friend = User.where(profile_name: params[:user_friendship][:friend_id]).first
			@user_friendship = UserFriendship.request(current_user, @friend)
			if @user_friendship.new_record?
				flash[:error] = "There was a problem creating this friendship."
			else
				flash[:success] = "Friend request sent."
			end
			redirect_to profile_path(@friend)
		else
			flash[:error] = "Friend required"
			redirect_to root_path
		end
	end

	def edit
		@user_friendship = current_user.user_friendships.find(params[:id]).decorate
		@friend = @user_friendship.friend
	end

	def destroy	
		@user_friendship = current_user.user_friendships.find(params[:id])
		if @user_friendship.destroy
			flash[:sucess] = "Friendship destroyed"
		end
		redirect_to user_friendships_path
	end
end

app/helpers/user_friendships_helper.rb
module UserFriendshipsHelper
end

app/views/user_friendships/edit.html.erb
<div class="page-header">
  <h1>Viewing Friendship</h1>
</div>

<h3><%= @user_friendship.sub_message %></h3>

<div class="form-actions">
  <% if @user_friendship.requested? %>
    <%= form_for @user_friendship, url: accept_user_friendship_path(@user_friendship), method: :put do |form| %>
      <%= submit_tag "Accept Friendship", class: 'btn btn-primary' %>
    <% end %>
  <% end %>

  <%= form_for @user_friendship, url: user_friendship_path(@user_friendship), method: :delete do |form| %>
    <%= submit_tag "Delete Friendship", class: 'btn btn-danger' %>
  <% end %>

</div>

app/views/user_friendships/index.html.erb
<div class="page-header">
  <h1>Friends</h1>
</div>

<% @user_friendships.each do |friendship| %>
  <% friend = friendship.friend %>
  <div id="<%= dom_id(friendship) %>" class="friend row">
    <div class="span1">
      <%= link_to image_tag(friend.gravatar_url), profile_path(friend) %>
    </div>
    <div class="span7">
      <strong><%= friend.full_name %></strong><br />
        <% if friendship.pending? %>
          <em>Friendship is pending.</em> <%= link_to "Delete request", edit_user_friendship_path(friendship) %>.
        <% end %>
        <% if friendship.requested? %>
          <em>Friendship requested.</em> <%= link_to "Accept Friendship", edit_user_friendship_path(friendship) %>.
        <% end %>
        <% if friendship.accepted? %>
          <em>Friendship started <%= friendship.updated_at %>.</em> <%= link_to "Update friendship", edit_user_friendship_path(friendship) %>.
        <% end %>
    </div>
  </div>
<% end %>

app/views/user_friendships/new.html.erb
<% if @friend %>
<!-- could call full_name on undefined if not first checking for @friend
 -->
 <h1><%= @friend.full_name %></h1>
 <p>Do you really want to friend <%= @friend.full_name %>?</p>
 <%= form_for @user_friendship, method: :post do |form| %>
	 	<div class="form form-actions">

	 		<!-- hidden field keeps track of friend_id when going from this form to the create action -->
	 		<%= form.hidden_field :friend_id, value: @friend.profile_name %>
	 		<%= submit_tag "Yes, Add Friend", class: 'btn btn-primary' %>
	 		<%= link_to "Cancel", profile_path(@friend), class: 'btn' %>
	 	</div>
 	<% end %>
<% end %>