config/routes.rb
Saved::Application.routes.draw do
  get "profiles/show"

  as :user do
    get "/register", to: "devise/registrations#new", as: :register
    get "/login", to: "devise/sessions#new", as: :login
    get "/logout", to: "devise/sessions#destroy", as: :logout
  end

  devise_for :users, skip: [:sessions]

  as :user do
    get "/login" => 'devise/sessions#new', as: :new_user_session
    post "/login" => 'devise/sessions#create', as: :user_session
    get "/logout" => 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :user_friendships do
    member do
      put :accept
    end
  end

  resources :testimonies
  get 'feed', to: 'testimonies#index', as: :feed
  root :to => "testimonies#index"

  get '/:id', to: 'profiles#show', as: 'profile'

end

app/models/testimony.rb
class Testimony < ActiveRecord::Base
  attr_accessible :content, :user_id
  belongs_to :user

  validates :content, presence: true,
  										length: { minimum: 2 }
  validates :user_id, presence: true										

end

app/controllers/testimonies_controller.rb
class TestimoniesController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update]
  # GET /testimonies
  # GET /testimonies.json
  def index
    @testimonies = Testimony.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @testimonies }
    end
  end

  # GET /testimonies/1
  # GET /testimonies/1.json
  def show
    @testimony = Testimony.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @testimony }
    end
  end

  # GET /testimonies/new
  # GET /testimonies/new.json
  def new
    @testimony = Testimony.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @testimony }
    end
  end

  # GET /testimonies/1/edit
  def edit
    @testimony = Testimony.find(params[:id])
  end

  # POST /testimonies
  # POST /testimonies.json
  def create
    @testimony = current_user.testimonies.new(params[:testimony])

    respond_to do |format|
      if @testimony.save
        format.html { redirect_to @testimony, notice: 'Testimony was successfully created.' }
        format.json { render json: @testimony, testimony: :created, location: @testimony }
      else
        format.html { render action: "new" }
        format.json { render json: @testimony.errors, testimony: :unprocessable_entity }
      end
    end
  end

  # PUT /testimonies/1
  # PUT /testimonies/1.json
  def update
    @testimony = current_user.testimonies.find(params[:id])
    if params[:testimony] && params[:testimony].has_key?(:user_id)
      params[:testimony].delete(:user_id) 
    end
    respond_to do |format|
      if @testimony.update_attributes(params[:testimony])
        format.html { redirect_to @testimony, notice: 'Testimony was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @testimony.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /testimonies/1
  # DELETE /testimonies/1.json
  def destroy
    @testimony = Testimony.find(params[:id])
    @testimony.destroy

    respond_to do |format|
      format.html { redirect_to testimonies_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/testimonies_helper.rb
module TestimoniesHelper
end

app/views/testimonies/_form.html.erb
<%= simple_form_for(@testimony, html: { class: "form-horizontal" }) do |f| %>
  <% if @testimony.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@testimony.errors.count, "error") %> prohibited this testimony from being saved:</h2>

      <ul>
      <% @testimony.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :content %>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/testimonies/edit.html.erb
<h1>Edit Testimony</h1><br />

<%= render 'form' %>

<%= link_to 'Show', @testimony %> |
<%= link_to 'Back', testimonies_path %>

app/views/testimonies/index.html.erb
<div class="page=header">
  <h1>All Testimonies</h1>
</div>

<% @testimonies.each do |testimony| %>
<div class="testimony">
  <div class="row">
    <div class="span1">

<!-- all models have to_param method that's called when passing the model into a URL helper like 'link_to'. ProfilesController show action is expecting 'name' rather than 'ID' to find the specified user though. Fixed by defining to_param method to return profile_name in users.rb
 -->      <%= link_to image_tag(testimony.user.gravatar_url), profile_path(testimony.user) %>
    </div>
    <div class="span7">
      <strong><%= testimony.user.full_name %></strong>
      <p><%= testimony.content %></p>
      <div class="meta">
        <%= link_to time_ago_in_words(testimony.created_at) + " ago", testimony %>
        <span class="admin">
        | <%= link_to "Edit", edit_testimony_path(testimony) %> |
        <%= link_to "Delete", testimony, method: :delete, data: { confirm: "Are you sure you'd like to delete this testimony?" }  %>
        </span>
      </div>
    </div>
  </div>
</div>
<br>
<% end %>  

<%= link_to "Post a New Testimony", new_testimony_path, class: "btn btn-success" %>

app/views/testimonies/new.html.erb
<h1>New Testimony</h1>

<%= render 'form' %>

<%= link_to 'Back', testimonies_path %>

app/views/testimonies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @testimony.user.full_name %>
</p>

<p>
  <b>Content:</b>
  <%= @testimony.content %>
</p>


<%= link_to 'Edit', edit_testimony_path(@testimony) %> |
<%= link_to 'Back', testimonies_path %>